### ISSUE TITLE
Django 1.8 support

### ISSUE THREAD

**Issue by barseghyanartur** [fusionbox/django-emailtools#12]
At the moment, tests fail on Django 1.8. Are there any plans to upgrade to Django 1.8?

**Comment by pipermerriam** [comment]
Not currently no. Happy to support you if you'd like to take a stab at it.

**Comment by barseghyanartur** [comment]
@pipermerriam:

Thanks for your quick reaction.

One of the sites just got to maintain uses this project as a dependency and we're estimating costs to upgrade to Django 1.8. If client accepts it, I'll be likely coming up with a pull request. Would you have any objections on throwing away support for Django versions older than 1.8?

**Comment by pipermerriam** [comment]
Fine too drop support for any versions of django that are no longer
officially supported.

**Comment by barseghyanartur** [comment]
Solved in pull request #13
