### ISSUE TITLE
Passing context data to the HTMLEmail

### ISSUE THREAD

**Issue by cyberjoac** [fusionbox/django-emailtools#4]
Hi, I really like your code, and it's by far the most elegant that I found for sending HTML emails.

I am trying to implement a "generic" class based view of email with templates, but I'm new to CBVs.
What would be the best way to go to implement it in a DRY way.

Especially, I am not sure how am I supposed to pass extra context for each email.
Assuming I do not want to create a custom class for each new mail, what would be the best way to pass a context_dictionary = {'var1': var1, 'var2': var2} at instantiation and render the templates with this context.

I could call it in such a way: email = Email("test subject", "template.html", "test@test.com", context_dictionary)
and then email.send().

By the way, is the reason you didn't implement it because it's not elegant enough?
Is it considered better style to create classes for each mail?

Thanks a lot for any help!
```python
class Email(HTMLEmail):
    def __init__(self, subject, template_name, to):
        self.template_name = template_name
        self.to = to
        self.subject = subject

    def get_context_data(self, **kwargs):
        kwargs = super(Email, self).get_context_data(**kwargs)
        # kwargs['user'] = self.user
        return kwargs

send_email = Email.as_callable()```

**Comment by pipermerriam** [comment]
> Is it considered better style to create classes for each mail?

This has typically been the pattern that I've used in most projects.  Most sites send a limited number of emails, and having a class for each one gives you good control over each individual email.

That said, if you still want to write a generic email class, the `as_callable(**initkwargs)` api will do most of the heavy lifting for you.

```python
class Email(HTMLEmail):
    extra_context = None

    def get_context_data(self, **kwargs):
        kwargs = super(Email, self).get_context_data(**kwargs)
        kwargs.update(self.extra_context or {})
        return kwargs

email_a = Email.as_callable(to='target@example.com', template_name=..., extra_context={'a': 1, 'b': 2})
```

The internals of `as_callable` dynamically construct a new email class using `initkwargs` to the dictionary of attributes the new class will have, and then returns a function that can be called to send that email.  All that you have to implement is the mechanism for passing in the extra template context.

**Comment by cyberjoac** [comment]
Thanks a lot for your fast and thorough answer.

I am now trying to send() in an asynchronous manner, and for this I tried to define an @task for an overriding send() function but for some reason it still sends synchronously...

    @task()
    def send(self):
        self.get_email_message().send(**self.get_send_kwargs())

And then I try to send like this:
            welcome_email = Email(subject="Welcome in! A quick question...",
                                  template_name='email/welcome/template.html',
                                  text_template='email/welcome/text_template.txt',
                                  to=activated_user.email, context_dict=locals())
            welcome_email.send.delay()

Thanks a lot for your help!!

**Comment by rockymeza** [comment]
You could try it like this:

```python
email_a = task(Email.as_callable(to='target@example.com', template_name=..., extra_context={'a': 1, 'b': 2}))
```

Then you can send emails just by calling the `email_a` function.

**Comment by pipermerriam** [comment]
Alternatively, I might suggest you doing this via a different mechanism using an email backend.

https://pypi.python.org/pypi/django-celery-email

That project is a whopping total of 51 lines of code that gives you an easy mechanism to move all of your mail sending to an asynchronous layer.

Not sure why your `@task` decorator isn't working, but I imagine that's more of an issue with how you're using celery.  I'm not familiar with decorating class methods as tasks.

**Comment by pipermerriam** [comment]
Also, @rockymeza's example is probably a good thing to try.

**Comment by pipermerriam** [comment]
Also, going to close this issue, feel free to continue to conversation.
